name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository }}/davical:$(date +%y%m%d)

    - name: Push the image to GPR
      run: |
        docker login docker.pkg.github.com -u publisher -p "${{ secrets.GITHUB_TOKEN }}"
        docker push docker.pkg.github.com/${{ github.repository }}/davical:$(date +%y%m%d)
